var FakeData = [
   {
     "name":"Modern HTML & CSS From The Beginning (Including Sass)",
     "intro":"Build modern responsive websites & UIs with HTML5, CSS3 & Sass! Learn Flex & CSS Grid",
     "created":"Brad Traversy",
     "time":"21 total hours. 129 lectures. All Levels",
     "img":"https://i.ibb.co/hVB8fZp/wp2742499.jpg",
     "price":"£134.99",
     "price1":9.99,
     "id":1,
   },
   {
    "name":"Build Responsive Real World Websites with HTML5 and CSS3",
    "intro":"The easiest way to learn modern web design, HTML5 and CSS3 step-by-step from scratch. Design AND code a huge project.",
    "created":"jonas Schmedtmann",
    "time":"12 total hours. 77 lectures. All Levels",
    "img":"https://i.ibb.co/3kT2pZd/413976bd.jpg",
    "price":"£129.99",
    "price1":9.99,
    "id":2,
  },
  {
    "name":"Build Responsive Website Using HTML5, CSS3, JS And Bootstrap",
    "intro":"Learn HTML5, CSS3, JavaScript, jQuery and Bootstrap framework by building a modern looking responsive website.",
    "created":"Irfan Dayan",
    "time":"8 total hours. 75 lectures. All Levels",
    "img":"https://i.ibb.co/rwNCX2Z/website-using-bootstrap-htm.jpg",
    "price":"£134.99",
    "price1":9.99,
    "id":3,
  },
  {
    "name":"The Bootstrap 4 Bootcamp",
    "intro":"Learn to build beautiful responsive websites with the latest Bootstrap version (4.1.3), Flexbox, HTML5, and CSS3!",
    "created":"Colt Steele",
    "time":"11.5 total hours. 87 lectures. Beginner",
    "img":"https://i.ibb.co/Tqzjq1s/334eufih5e0xc8pm67fu.webp",
    "price":"£119.99",
    "price1":9.99,
    "id":4,
  },
  {
    "name":"Bootstrap 4 Tutorial and 10 Projects Course",
    "intro":"Step by Step learn Bootstrap 4 with tutorial and by creating 10 interesting projects.",
    "created":"john Smilga",
    "time":"44 total hours. 249 lectures. All Levels",
    "img":"https://i.ibb.co/tmRQmpv/twitter-bootstrap-plugin.png",
    "price":"£134.99",
    "price1":9.99,
    "id":5,
  },
  {
    "name":"Modern JavaScript From The Beginning",
    "intro":"Learn and build projects with pure JavaScript (No frameworks or libraries)",
    "created":"Brad Traversy",
    "time":"21.5 total hours. 122 lectures. All Levels",
    "img":"https://i.ibb.co/c8CpvFs/javascript-cover.webp",
    "price":"£144.99",
    "price1":9.99,
    "id":6,
  },
  {
    "name":"JavaScript - The Complete Guide 2020 (Beginner + Advanced)",
    "intro":"Modern JavaScript from the beginning - all the way up to JS expert level! THE must-have JavaScript resource in 2020.",
    "created":"Maximilian Schwarzmuller",
    "time":"52.5 total hours. 614 lectures. All Levels",
    "img":"https://i.ibb.co/s56WsPt/cc5eb3a8399d.jpg",
    "price":"£134.99",
    "price1":9.99,
    "id":7,
  },
  {
    "name":"React - The Complete Guide (incl Hooks, React Router, Redux)",
    "intro":"Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!",
    "created":"Maximilian Schwarzmuller",
    "time":"40.5 total hours. 490 lectures. All Levels",
    "img":"https://i.ibb.co/JvX8Vz4/5753173610332160.png",
    "price":"£134.99",
    "price1":9.99,
    "id":8,
  },
  {
    "name":"Advanced React and Redux",
    "intro":"Walkthroughs on advanced React v16.6.3 and Redux v4.0.0 - Authentication, Testing, Middlewares, HOC's, and Deployment",
    "created":"Stephen Grider",
    "time":"21 total hours. 239 lectures. intermediate",
    "img":"https://i.ibb.co/Dr8DtjX/8a14e204.jpg",
    "price":"£134.99",
    "price1":9.99,
    "id":9,
  },
  {
    "name":"The Complete Angular Course: Beginner to Advanced",
    "intro":"The most comprehensive Angular 4 (Angular 2+) course. Build a real e-commerce app with Angular, Firebase and Bootstrap 4",
    "created":"Mosh Hamedani",
    "time":"29.5 total hours.376 lectures. All Levels",
    "img":"https://i.ibb.co/ggCVnGt/Angular-JS-Complete-Course.jpg",
    "price":"£99.99",
    "price1":9.99,
    "id":10,
  },
  {
    "name":"Angular Crash Course for Busy Developers",
    "intro":"Have limited time to learn Angular 4 (Angular 2+)? Take this course and learn Angular in 10 hours!",
    "created":"Mosh Hamedani",
    "time":"10.5 total hours. 137 lectures. All Levels",
    "img":"https://i.ibb.co/hFkH0VF/1-p-K-tm-Nd0o-H1yhu-TBg70-H7-A.jpg",
    "price":"£134.99",
    "price1":9.99,
    "id":11,
  },
  {
    "name":"Vue JS - The Complete Guide (incl. Vue Router & Vuex)",
    "intro":"Vue.js is an awesome JavaScript Framework for building Frontend Applications! VueJS mixes the Best of Angular + React!",
    "created":"Maximilian Schwarzmuller",
    "time":"21 total hours. 129 lectures. All Levels",
    "img":"https://i.ibb.co/Y80Qqpx/cover-Vue.png",
    "price":"£134.99",
    "price1":9.99,
    "id":12,
  },
  {
    "name":"Vue.js Essentials - 3 Course Bundle",
    "intro":"Learn and master VueJS by building 3 professional, real world web application using Vue!",
    "created":"Anthony Gore",
    "time":"12.5 total hours. 182 lectures. All Levels",
    "img":"https://i.ibb.co/sstSC4S/unnamed.png",
    "price":"£134.99",
    "price1":9.99,
    "id":13,
  },
  {
    "name":"The Complete Front-End Web Development Course!",
    "intro":"Get started as a front-end web developer using HTML, CSS, JavaScript, jQuery, and Bootstrap!",
    "created":"Nick Germaine",
    "time":"17 total hours. 126 lectures. All Levels",
    "img":"https://i.ibb.co/qxP4Hd6/30e4c5-94ab93fae57f4a94b1ac4fda75ecd1e0-mv2.jpg",
    "price":"£134.99",
    "price1":9.99,
    "id":14,
  },
  {
    "name":"Front End Web Development For Beginners (A Practical Guide)",
    "intro":"Learn Front-End Web Development: Quickly Master HTML5, CSS3, JS, Bootstrap: By Building A Project From Scratch",
    "created":"Learn Tech Plus",
    "time":"34 total hours. 383 lectures. Beginner",
    "img":"https://i.ibb.co/SQSnJJj/Front-End-Development-Frameworks.jpg",
    "price":"£134.99",
    "price1":9.99,
    "id":15,
  },
]
export default FakeData;
